[project]
name = "zmag"
dynamic = ["version"]
description = "Craft APIs with ZeroMQ and GraphQL"
authors = [
    { name = "hlop3z", email = "23062270+hlop3z@users.noreply.github.com" },
]
requires-python = ">=3.12"
readme = "README.md"
license = { text = "MIT" }
dependencies = ["pyzmq>=26.2.0", "orjson>=3.10.7"]

[project.optional-dependencies]
debug = ["uvicorn[standard]>=0.30.6", "starlette>=0.38.2", "watchdog>=4.0.2"]
server = ["spoc>=0.1.35", "strawberry-graphql>=0.237.3", "click>=8.1.7"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/zmag/__init__.py"

[tool.uv]
dev-dependencies = [
    "pyright>=1.1.377",
    "mypy>=1.11.1",
    "isort>=5.13.2",
    "black>=24.8.0",
    "pylint>=3.2.6",
    "ruff>=0.6.2",
    "bandit>=1.7.9",
    "watchdog>=4.0.2",
    "ssort>=0.13.0",
    "mkdocs>=1.6.0",
    "mkdocs-material>=9.5.32",
    "mkdocs-macros-plugin>=1.0.5",
    "mkdocstrings[python]>=0.25.2",
    "termynal>=0.12.1",
]

[tool.uv.sources]
# zmag = { workspace = true }
