[project]
name = "zmag"
version = "0.0.9"
description = "Craft APIs for Databases, with ZeroMQ and GraphQL"
authors = [
    { name = "hlop3z", email = "23062270+hlop3z@users.noreply.github.com" },
]
requires-python = ">=3.12"
readme = "README.md"
license = { text = "MIT" }
dependencies = ["pyzmq>=25.1.1"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[project.scripts]
startproject = "zmag.scripts.start_project:cli"

[project.optional-dependencies]
debug = [
    "ariadne>=0.20.1",
    "spoc>=0.1.12",
    "click>=8.1.7",
    "dbcontroller[mongo,sql,sqlite]>=0.1.57",
    "uvicorn[standard]>=0.23.2",
    "watchdog>=3.0.0",
]
sqlite = [
    "ariadne>=0.20.1",
    "spoc>=0.1.12",
    "click>=8.1.7",
    "dbcontroller[sqlite]>=0.1.57",
]
postgresql = [
    "ariadne>=0.20.1",
    "spoc>=0.1.12",
    "click>=8.1.7",
    "dbcontroller[sql]>=0.1.57",
    "databases[asyncpg]>=0.8.0",
]
mysql = [
    "ariadne>=0.20.1",
    "spoc>=0.1.12",
    "click>=8.1.7",
    "dbcontroller[sql]>=0.1.57",
    "databases[aiomysql]>=0.8.0",
]


[tool]
[tool.pdm]
[tool.pdm.dev-dependencies]
devs = [
    "notebook>=7.0.6",
    "dbcontroller[mongo,sql,sqlite]>=0.1.57",
    "uvicorn[standard]>=0.23.2",
    "ariadne>=0.20.1",
    "watchdog>=3.0.0",
]
service = ["spoc>=0.1.12", "click>=8.1.7"]

[tool.pdm.scripts]
# Develop
test = { shell = "cd tests && python main.py" }
test-client = { shell = "cd client_tests && python test.py" }
# Notebook
notebook = { shell = "python -m jupyter notebook" }
