"""empty message

Revision ID: e7024b20f192
Revises: d245cbed3ca7
Create Date: 2023-11-01 22:21:46.435922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7024b20f192'
down_revision = 'd245cbed3ca7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
