# Application Configuration
[spoc]
mode = "development" # options: (development, staging, production)
debug = true

[spoc.api]
name = "ZMAG API"
docs = true
html = true
version = "0.4.0"
description = "API for managing items, including creation, retrieval, updates, and deletion."

# Installed Apps by Mode
[spoc.apps]
production = ["auth", "sample_app"]
staging = []
development = []

# Additional Components (Plugins and Hooks)
[spoc.plugins]
#middleware = ["demo.extras.middleware"]
#hooks = ["demo.extras.hook"]
