site_name: Zmag
site_url: https://hlop3z.github.io/zmag
repo_url: https://github.com/hlop3z/zmag
copyright: Copyright © Hlop3z

nav:
  - Introduction: index.md
  - Settings: settings.md
  - Commands: commands.md
  - Schema: schema.md
  - Manager: manager.md
  - Client: client.md
  - SQL Database:
      - Migrations: databases/index.md

# Configurations
watch:
  - custom_theme

theme:
  custom_dir: custom_theme/
  name: material
  locale: en
  features:
    # - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - content.code.annotate
    # - navigation.expand
  icon:
    logo: material/lan

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
