# Configurations
site_name: ZMAG
site_url: https://hlop3z.github.io/zmag/
repo_url: https://github.com/hlop3z/zmag/
copyright: Copyright © Hlop3z

# Navigation
nav:
  - ZMAG:
      - Introduction: index.md
      - Use Cases: use-cases.md
      - Motivation: motivation.md
  - Server:
      - Constant: server/config/variables.md
      - Settings: server/config/settings.md
      - Environment: server/config/environment.md
      - CLI:
          - Commands: server/commands.md
      - GraphQL:
          - Types: server/graphql/types.md
          - Inputs: server/graphql/inputs.md
          - Operations: server/graphql/operations.md
          - Built-In: server/graphql/built-in.md
      - ZMQ:
          - Queue: server/queue.md
          - Streamer: server/streamer.md
          - Forwarder: server/forwarder.md
          - Proxy Device: server/devices.md
          - Authentication: server/authentication.md
  - Client:
      - Requests: client/requests.md
      - Sub/Pull: client/sub-pull.md
      - Authentication: client/authentication.md
  - Reference:
      - Demo: api/api.md
      - ZeroMQ: api/zeromq.md
      - GraphQL: api/graphql.md
      - Commands: api/cli.md
      - Client: api/client.md

# Path Watch
watch:
  - custom_theme
  - ../src

# Extras
extra:
  generator: false

# Theme
theme:
  custom_dir: custom_theme/
  name: material
  locale: en
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  features:
    - content.code.annotate
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - admonition
  - tables
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.tasklist:
      custom_checkbox: true

# Plugins
plugins:
  - search

  # Macros
  - macros:
      modules:
        - macros

  # termynal
  - termynal

  # mkdocstrings
  - mkdocstrings:
      handlers:
        python:
          paths: [..] # search packages in the src folder
          options:
            # Docstring Style
            docstring_style: google
            docstring_section_style: list # table | list | spacy

            # Symbol
            show_symbol_type_toc: true
            show_symbol_type_heading: false

            # Headings
            show_root_heading: true
            separate_signature: false

            # Generic
            allow_inspection: true
            group_by_category: true
            show_bases: false
            show_labels: true
            show_source: false
            unwrap_annotated: true

            # Members
            members_order: source
            inherited_members: false

            # Object Paths
            show_root_members_full_path: false
            show_object_full_path: false

            # Init
            merge_init_into_class: true
            docstring_options:
              ignore_init_summary: true

            # Docstring Include
            show_docstring_functions: false
            show_docstring_examples: false
            show_if_no_docstring: false

            # Filters
            filters:
              - "!^_"
